name: Build & Deploy Angular → GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Installer les dépendances
        run: npm install
      - name: Builder l'app
        run: npm run build -- --configuration production --base-href /PokeRixe/
      - name: Copier index.html en 404.html
        run: cp ./dist/client/browser/index.html ./dist/client/browser/404.html
      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/client/browser
